bot.name :
  TeacherLCbot
bot.token :
  6974082636:AAGfYI3itukP3nGzdIS4e5CVP1iY9jP1keY

spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:11291/railway
    username: postgres
    password: 26af1Ea2Gb3CBcdfEecA-EB-b5FBd5ae
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect